export default function useCustomersOptions() {
  const statusOptions = [
    { label: 'Pending', value: 'pending' },
    { label: 'Active', value: 'active' },
    { label: 'Inactive', value: 'inactive' },
  ]
  const areaOptions = [
    { label: 'Area 01', value: 'Area 01 ' },
    { label: 'Area 02', value: 'Area 02' },
    { label: 'Area 03', value: 'Area 03' },
    { label: 'Area 04', value: 'Area 04' },
    { label: 'Area 05', value: 'Area 05' },
    { label: 'Area 06', value: 'Area 06' },
    { label: 'Area 07', value: 'Area 07' },
    { label: 'Area 08', value: 'Area 08' },
    { label: 'Area 09', value: 'Area 09' },
    { label: 'Area 10', value: 'Area 10' },
  ]
  const categoryOptions = [
    { label: 'Fire Extinguisher', value: 'Fire Extinguisher' },
    { label: 'Fire Hoses', value: 'Fire Hoses' },
    { label: 'Fire Sprinklers', value: 'Fire Sprinklers' },
    { label: 'Smoke Detectors', value: 'Smoke Detectors' },
    { label: 'Fire Alarms', value: 'Fire Alarms' },
    { label: 'Fire Suppression Systems', value: 'Fire Suppression Systems' },
  ]
  const durationOptions = [
    { label: '01 year', value: '01year' },
    { label: '02 years', value: '02years' },
    { label: '03 years', value: '03years' },
    { label: '04 years', value: '04years' },
    { label: '05 years', value: '05 years' },
    { label: 'Contract of indefinite duration', value: 'contractOfIndefiniteDuration' },
  ]
  const locationDescriptionOptions = [
    'Warehouse',
    'Shop',
    'Office',
    'Factory',
    'Showroom',
    'Training center',
    'Laboratory',
    'Distribution center',
    'Gym',
    'Restaurant',
    'Clinic',
    'Theater',
    'Service center',
    'Conference center',
    'Museum',
    'Library',
    'Park',
    'Marina',
  ]
  const openingOptions = [
    '24/7',
    'Open seven days a week',
    'Monday-Friday, 8am-5pm, closed on weekends.',
    'Monday-Saturday, 8am-5pm, Sunday closed.',
    'Open day and night',
  ]
  const planOptions = [
    { label: 'Basic Plan', value: 'Basic' },
    { label: 'Basic Plus Plan', value: 'Basic Plus' },
    { label: 'Company Plan', value: 'Company' },
    { label: 'Entreprise Plan', value: 'Entreprise' },
    { label: 'Elite Plan', value: 'Elite' },
  ]
  const paymentMethodOptions = [
    { label: 'Bank Transfer', value: 'banktransfer' },
    { label: 'Bank Check', value: 'check' },
    { label: 'Bank Draft', value: 'draft' },
    { label: 'Cash', value: 'cash' },
    { label: 'Credit Card', value: 'creditcard' },
  ]
  const paymentDeadlineOptions = [
    { label: 'Advance', value: 'Advance' },
    { label: 'Upon Completion', value: 'Upon Completion' },
    { label: 'Bi-monthly', value: 'bi-Monthly' },
    { label: 'Net 07 days', value: 'Net 07 days' },
    { label: 'Net 15 days', value: 'Net 15 days' },
    { label: 'Net 30 days', value: 'Net 30 days' },
    { label: 'Net 60 days', value: 'Net 60 days' },
    { label: 'Net 90 days', value: 'Net 90 days' },
    { label: 'Monthly', value: 'Monthly' },
    { label: 'Progress', value: 'Progress' },
    { label: 'End of Project', value: 'End of Project' },
  ]
  const sendingTypeOptions = [
    'Purchase Order',
    'Phone',
    'Email',
    'Online',
    'In-store',
    'SMS',
    'Whatsapp',
    'Fax',
  ]
  const exclusivityClause = [
    { text: 'Active', value: '1' },
    { text: 'Inactive', value: '0' },
  ]

  const genderOptions = [
    { text: 'Male', value: 'male' },
    { text: 'Female', value: 'female' },
  ]
  const contactTypeOptions = ['Email', 'Message', 'Phone']

  const languageOptions = ['English', 'Spanish', 'French', 'Russian', 'German', 'Arabic', 'Italian']

  const cityOptions = [
    'tunis',
    'sousse',
    'ben arous',
    'sfax',
    'bizerte',
    'kairouan',
    'gabès',
    'jendouba',
    'ariana',
    'nabeul',
    'zaghouan',
    'hammamet',
    'monastir',
    'kasserine',
    'gafsa',
    'Kébili',
    'sidi bouzid',
    'tozeur',
    'tataouine',
    'manouba',
    'mahdia',
    'siliana',
    'kef',
  ]
  const countryOptions = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    "Côte d'Ivoire",
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Holy See',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine State',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent & the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'USA',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ]
  return {
    // All Customer Module Options
    categoryOptions,
    areaOptions,
    statusOptions,
    locationDescriptionOptions,
    sendingTypeOptions,
    exclusivityClause,
    paymentMethodOptions,
    paymentDeadlineOptions,
    planOptions,
    openingOptions,
    durationOptions,
    genderOptions,
    contactTypeOptions,
    languageOptions,
    cityOptions,
    countryOptions,
  }
}
