export default function useCustomersOptions() {
  const statusOptions = [
    { label: 'Pending', value: 'pending' },
    { label: 'Completed', value: 'completed' },
    { label: 'In Progress', value: 'in_progress' },
  ]
  const typeOptions = [
    { label: 'Intervention', value: 'intervention ' },
    { label: 'Assistance ', value: 'assistance' },
  ]
  const frequencyOptions = [
    { label: 'Quarterly', value: 'quarterly ' },
    { label: 'Half-yearly', value: 'half-yearly' },
    { label: 'Yearly', value: 'Yearly' },
  ]
  const activityOptions = [
    { label: 'Agrifood', value: 'agrifood' },
    { label: 'Bank / Insurance', value: 'bank Insurance' },
    { label: 'Wood / Paper / Cardboard / Printing', value: 'wood Paper Cardboard Printing' },
    { label: 'Construction / Building materials', value: 'construction Building materials' },
    { label: 'Chemistry / Parachemistry', value: 'chemistry Parachemistry' },
    { label: 'Trade / Trading / Distribution', value: 'trade Trading Distribution' },
    { label: 'Publishing / Communication / Multimedia', value: 'publishing Communication Multimedia' },
    { label: 'Electronics / Electricity', value: 'electronics Electricity' },
    { label: 'Studies / Advice', value: 'studiesAdvice' },
    { label: 'Pharmaceutical Industry', value: 'pharmaceutical Industry' },
    { label: 'IT / Telecoms', value: 'it Telecoms' },
    { label: 'Machinery and equipment / Automotive', value: 'machinery And Equipment Automotive' },
    { label: 'Metallurgy / Metalworking', value: 'metallurgy Metal working' },
    { label: 'Plastic / Rubber', value: 'plastic Rubber' },
    { label: 'Business Services', value: 'business Services' },
    { label: 'Textile / Clothing / Footwear', value: 'textile Clothing Footwear' },
    { label: 'Transport / Logistics', value: 'transport Logistics' },
    { label: 'Non-Profit', value: 'non Profit' },
    { label: 'Educational', value: 'educational' },
  ]
  const durationOptions = [
    { label: '01 year', value: '01year' },
    { label: '02 years', value: '02years' },
    { label: '03 years', value: '03years' },
    { label: '04 years', value: '04years' },
    { label: '05 years', value: '05 years' },
    { label: 'Contract of indefinite duration', value: 'contractOfIndefiniteDuration' },
  ]
  const serviceDescriptionOptions = [
    { service: 'Regular fire extinguisher maintenance', type: 'Maintenance' },
    { service: 'Regular fire hose maintenance', type: 'Maintenance' },
    { service: 'Regular fire system maintenance', type: 'Maintenance' },
    { service: 'Fire suppression system installation and maintenance', type: 'Maintenance' },
    { service: 'Sprinkler system inspection and maintenance', type: 'Maintenance' },
    { service: 'Regular fire system inspection', type: 'Inspection' },
    { service: 'Installation and placement assessment for fire equipments', type: 'Installation' },
    { service: 'Installation of proper signage for fire equipments', type: 'Installation' },
    { service: 'Replacement of signs as needed', type: 'Installation' },
    { service: 'Fire extinguisher training and education', type: 'Assistance' },
    { service: 'Fire risk assessment', type: 'Assistance' },
    { service: 'Identification and labeling of fire equipments', type: 'Assistance' },
    { service: 'Safety audits and reports', type: 'Assistance' },
    { service: 'Record keeping and documentation management', type: 'Assistance' },
    { service: 'Development of a fire protection plan for a building or facility', type: 'Assistance' },
    { service: 'Fire suppression system design and engineering', type: 'Assistance' },
    { service: 'Fire System testing and certification', type: 'Assistance' },
    { service: 'Emergency response services for maintenance and other emergencies', type: 'Emergency' },
  ]

  const openingOptions = [
    '24/7',
    'Open seven days a week',
    'Monday-Friday, 8am-5pm, closed on weekends.',
    'Monday-Saturday, 8am-5pm, Sunday closed.',
    'Open day and night',
  ]
  const planOptions = [
    { label: 'Basic Plan', value: 'Basic' },
    { label: 'Basic Plus Plan', value: 'Basic Plus' },
    { label: 'Company Plan', value: 'Company' },
    { label: 'Entreprise Plan', value: 'Entreprise' },
    { label: 'Elite Plan', value: 'Elite' },
  ]
  const paymentMethodOptions = [
    { label: 'Bank Transfer', value: 'banktransfer' },
    { label: 'Bank Check', value: 'check' },
    { label: 'Bank Draft', value: 'draft' },
    { label: 'Cash', value: 'cash' },
    { label: 'Credit Card', value: 'creditcard' },
  ]
  const paymentDeadlineOptions = [
    { label: 'Advance', value: 'Advance' },
    { label: 'Upon Completion', value: 'Upon Completion' },
    { label: 'Bi-monthly', value: 'bi-Monthly' },
    { label: 'Net 07 days', value: 'Net 07 days' },
    { label: 'Net 15 days', value: 'Net 15 days' },
    { label: 'Net 30 days', value: 'Net 30 days' },
    { label: 'Net 60 days', value: 'Net 60 days' },
    { label: 'Net 90 days', value: 'Net 90 days' },
    { label: 'Monthly', value: 'Monthly' },
    { label: 'Progress', value: 'Progress' },
    { label: 'End of Project', value: 'End of Project' },
  ]
  const sendingTypeOptions = [
    'Purchase Order',
    'Phone',
    'Email',
    'Online',
    'In-store',
    'SMS',
    'Whatsapp',
    'Fax',
  ]
  const exclusivityClause = [
    { text: 'Active', value: '1' },
    { text: 'Inactive', value: '0' },
  ]

  const genderOptions = [
    { text: 'Male', value: 'male' },
    { text: 'Female', value: 'female' },
  ]
  const contactTypeOptions = ['Email', 'Message', 'Phone']

  const languageOptions = ['English', 'Spanish', 'French', 'Russian', 'German', 'Arabic', 'Italian']

  const cityOptions = [
    'tunis',
    'sousse',
    'ben arous',
    'sfax',
    'bizerte',
    'kairouan',
    'gabès',
    'jendouba',
    'ariana',
    'nabeul',
    'zaghouan',
    'hammamet',
    'monastir',
    'kasserine',
    'gafsa',
    'Kébili',
    'sidi bouzid',
    'tozeur',
    'tataouine',
    'manouba',
    'mahdia',
    'siliana',
    'kef',
  ]
  const countryOptions = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    "Côte d'Ivoire",
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Holy See',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine State',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent & the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'USA',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ]
  return {
    // All Customer Module Options
    activityOptions,
    typeOptions,
    frequencyOptions,
    statusOptions,
    serviceDescriptionOptions,
    sendingTypeOptions,
    exclusivityClause,
    paymentMethodOptions,
    paymentDeadlineOptions,
    planOptions,
    openingOptions,
    durationOptions,
    genderOptions,
    contactTypeOptions,
    languageOptions,
    cityOptions,
    countryOptions,
  }
}
